// <auto-generated />
using DndMonsterApp.DataAccess.Sql.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DndMonsterApp.DataAccess.Sql.Migrations
{
    [DbContext(typeof(MonsterAppDbContext))]
    [Migration("20201201233706_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DndMonsterApp.DataAccess.Sql.Entities.ChallengeRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("AttackBonus")
                        .HasColumnType("int");

                    b.Property<int>("MaximumDamage")
                        .HasColumnType("int");

                    b.Property<int>("MaximumHitPoints")
                        .HasColumnType("int");

                    b.Property<int>("MinimumDamage")
                        .HasColumnType("int");

                    b.Property<int>("MinimumHitPoints")
                        .HasColumnType("int");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("int");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SavingsThrowDc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChallengeRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
